targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/**
      json_serializable:
        generate_for:
          include:
            - lib/models/**
        options:
          explicit_to_json: true
          field_rename: snake
      riverpod_generator:
        generate_for:
          include:
            - lib/providers/**
